services:
  - type: web
    name: tiksaver-pro-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RAPIDAPI_KEY
        value: 50ba3beb9dmsh32e482dfd3b8de0p186df1jsnc8e1c4bf14e3
      - key: RAPIDAPI_HOST
        value: tiktok-trending1.p.rapidapi.com
